Vagrant.configure("2") do |config|
    config.vm.box = "laravel/homestead"
    config.vm.synced_folder ".", "/home/vagrant/code"

    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "whatever.com"
end